### PR TITLE
Account for changes of of_get_mac_address in 5.13

### PR DESCRIPTION
**Pull request by jan-kiszka**

### CODE REVIEW

**Comment by fifteenhex** [comment]
Hi, Sorry for some reason I don't get notifications... You've tested this right? I don't have the hardware to check at hand.

**Comment by fifteenhex** [comment]
There was another PR that had some test results on it so I used that one. Thanks though!

**Comment by jan-kiszka** [comment]
The other patch looks wrong /wrt random MAC fallback. Seem to have happened along its code duplication. Will try to fix.

**Comment by jan-kiszka** [comment]
False alarm, just a bit ugly. Will re-test master now.

**Pull request closed without merging**
